Spring13 add : User, Item;
PolinKartav/java-shareit pull request #1
Opened 2023-07-09 17:38 UTC by PolinKartav

2023-07-10 07:12 UTC, alexache requested changes

2023-07-10 07:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private String request;
Уже есть класс ItemRequest, можно сразу на него ссылку добавлять

2023-07-10 07:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        for (Item item : items) {
(опционально) можно воспользоваться стримами, чтобы это выглядело изящнее

2023-07-10 07:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +            return Optional.of(items.get(id).toBuilder().build());
А для чего эта манипуляция?

2023-07-10 07:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +        itemsWithUsers.computeIfAbsent(ownerId, k -> new HashMap<>()).put(itemId, item);
А нужно ли хранить в мапе юзера на его вещи еще одну мапу или будет достаточно маппинга юзера на простой список?

2023-07-10 07:12 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        if (emails.contains(user.getEmail()) && !users.get(user.getId()).getEmail().equals(user.getEmail())) {
users.get() вызывается от 1 до 2 раз, можно сделать, чтобы всегда было 1 раз

2023-07-10 15:59 UTC, PolinKartav commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +            return Optional.of(items.get(id).toBuilder().build());
Чтобы возвращалась копия

2023-07-10 16:00 UTC, PolinKartav commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        for (Item item : items) {
Знаю, что потоки удобнее, решила написать несколько вариантов

2023-07-10 16:01 UTC, PolinKartav commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private String request;
Спасибо, изменю

2023-07-10 16:02 UTC, PolinKartav commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +        itemsWithUsers.computeIfAbsent(ownerId, k -> new HashMap<>()).put(itemId, item);
Думаю, что при хранение хранение мапы более удобно, если в дальнейшем понадобится поиск по товарам юзера

2023-07-10 16:08 UTC, PolinKartav commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        if (emails.contains(user.getEmail()) && !users.get(user.getId()).getEmail().equals(user.getEmail())) {
Не очень понимаю, о чем Вы

2023-07-11 16:04 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +            return Optional.of(items.get(id).toBuilder().build());
Это не столь актуально, учитывая, что все равно все в ДТО перекладывается

2023-07-11 16:05 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +        itemsWithUsers.computeIfAbsent(ownerId, k -> new HashMap<>()).put(itemId, item);
Когда понадобится, тогда можно и переделать

2023-07-11 16:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        if (emails.contains(user.getEmail()) && !users.get(user.getId()).getEmail().equals(user.getEmail())) {
внутри данного метода (updateUser) есть 2 вызова метода users.get(), а можно вызывать единожды и сохранять результат в переменную

2023-07-11 16:10 UTC, alexache approved these changes

2023-07-21 15:49 UTC, merged