Sprint 15 : added request, tests;
PolinKartav/java-shareit pull request #3
Opened 2023-08-23 21:34 UTC by PolinKartav

2023-08-24 18:34 UTC, alexache requested changes

2023-08-24 18:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +   // @Column(name = "request_id")
Много закомментированных аннотаций, что-то пошло не так?

2023-08-24 18:34 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Data
Эту аннотацию нельзя применять на JPA модели

2023-08-24 18:34 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    private static ItemService itemService;
А зачем все поля делать статичными?

2023-08-24 21:32 UTC, PolinKartav commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +   // @Column(name = "request_id")
Я просто по разному пробую и потом забываю удалять комменты, спасибо, поправлю

2023-08-24 21:41 UTC, PolinKartav commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    private static ItemService itemService;
Все поля не нужно, но объекты классов моделей статичные, иначе к ним нельзя будет обращаться из статичных контекстов

2023-08-25 19:05 UTC, alexache commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +    private static ItemService itemService;
Модели ок, а вот другие сущности не стоит

2023-08-25 19:08 UTC, alexache requested changes
В ревьюилке я ещё писал комментарий про недостающие тесты  на репозитории

2023-08-25 19:08 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +
@getter / @setter допустимы, проблема в @equalsandhashcode

2023-08-28 05:38 UTC, alexache approved these changes

2023-08-28 05:38 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    BookingRepository bookingRepository;
У полей (даже теста)  модификаторы доступа принято писать, хотя это и субъективно

2023-08-28 05:38 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void shouldGet2BookingWithFindAllByBookerId() {
Тесты нужны только на методы, где есть @Query

2023-08-28 16:11 UTC, PolinKartav commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    BookingRepository bookingRepository;
поняла, спасибо, учту

2023-08-28 16:12 UTC, merged